# This cask is auto-generated by CI in AISquare-Studio/team-os on each release.
# The version + sha256 below are placeholders until the first automated release runs.
cask "team-os" do
  version "0.0.0"
  sha256 :no_check

  url "https://github.com/AISquare-Studio/homebrew-teamos/releases/latest/download/Team-OS-macos-arm64.dmg"
  name "Team OS"
  desc "AISquare Team OS desktop app"
  homepage "https://github.com/AISquare-Studio/team-os"

  depends_on arch: :arm64

  app "Team OS.app"

  postflight do
    system_command "/usr/bin/xattr",
                   args: ["-dr", "com.apple.quarantine", "#{appdir}/Team OS.app"]
  end
end
